// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdklkqessulfnjbawpfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBka2xrcWVzc3VsZm5qYmF3cGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTMxNzUsImV4cCI6MjA3MTQ2OTE3NX0.i3-ypz6077VvUZu0SyFp_bugQBBdBdDi706Xcwnz1WE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});